/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VoteSlugRouteImport } from './routes/vote/$slug'
import { Route as ContestantsIdEditRouteImport } from './routes/contestants/$id/edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteSlugRoute = VoteSlugRouteImport.update({
  id: '/vote/$slug',
  path: '/vote/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestantsIdEditRoute = ContestantsIdEditRouteImport.update({
  id: '/contestants/$id/edit',
  path: '/contestants/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/register': typeof RegisterRoute
  '/vote/$slug': typeof VoteSlugRoute
  '/contestants/$id/edit': typeof ContestantsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/register': typeof RegisterRoute
  '/vote/$slug': typeof VoteSlugRoute
  '/contestants/$id/edit': typeof ContestantsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/register': typeof RegisterRoute
  '/vote/$slug': typeof VoteSlugRoute
  '/contestants/$id/edit': typeof ContestantsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leaderboard'
    | '/register'
    | '/vote/$slug'
    | '/contestants/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard'
    | '/register'
    | '/vote/$slug'
    | '/contestants/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/leaderboard'
    | '/register'
    | '/vote/$slug'
    | '/contestants/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardRoute: typeof LeaderboardRoute
  RegisterRoute: typeof RegisterRoute
  VoteSlugRoute: typeof VoteSlugRoute
  ContestantsIdEditRoute: typeof ContestantsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote/$slug': {
      id: '/vote/$slug'
      path: '/vote/$slug'
      fullPath: '/vote/$slug'
      preLoaderRoute: typeof VoteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contestants/$id/edit': {
      id: '/contestants/$id/edit'
      path: '/contestants/$id/edit'
      fullPath: '/contestants/$id/edit'
      preLoaderRoute: typeof ContestantsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRoute,
  RegisterRoute: RegisterRoute,
  VoteSlugRoute: VoteSlugRoute,
  ContestantsIdEditRoute: ContestantsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
